In [ ]:
import pandas as pd
import sqlite3 as sql
df = pd.read_csv('ab_data.csv')
df

        user_id                   timestamp      group landing_page  converted
0        851104  2017-01-21 22:11:48.556739    control     old_page          0
1        804228  2017-01-12 08:01:45.159739    control     old_page          0
2        661590  2017-01-11 16:55:06.154213  treatment     new_page          0
3        853541  2017-01-08 18:28:03.143765  treatment     new_page          0
4        864975  2017-01-21 01:52:26.210827    control     old_page          1
...         ...                         ...        ...          ...        ...
294473   751197  2017-01-03 22:28:38.630509    control     old_page          0
294474   945152  2017-01-12 00:51:57.078372    control     old_page          0
294475   734608  2017-01-22 11:45:03.439544    control     old_page          0
294476   697314  2017-01-15 01:20:28.957438    control     old_page          0
294477   715931  2017-01-16 12:40:24.467417  treatment     new_page          0

[294478 rows x 5 columns]

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 294478 entries, 0 to 294477
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   user_id       294478 non-null  int64
 1   timestamp     294478 non-null  str
 2   group         294478 non-null  str
 3   landing_page  294478 non-null  str
 4   converted     294478 non-null  int64
dtypes: int64(2), str(3)
memory usage: 23.0 MB

In [ ]:
#no nulls no NaN

In [ ]:
# Find duplicates excluding timestamp column
duplicates = df[df.drop(columns=['timestamp']).duplicated(keep=False)]
print(duplicates)

      user_id                   timestamp      group landing_page  converted
1899   773192  2017-01-09 05:37:58.781806  treatment     new_page          0
2893   773192  2017-01-14 02:55:59.590927  treatment     new_page          0

In [ ]:
#there is 1 exact copy
# Keep first occurrence, remove later duplicates
df = df.drop_duplicates(subset='user_id', keep='first')

print(df)

        user_id                   timestamp      group landing_page  converted
0        851104  2017-01-21 22:11:48.556739    control     old_page          0
1        804228  2017-01-12 08:01:45.159739    control     old_page          0
2        661590  2017-01-11 16:55:06.154213  treatment     new_page          0
3        853541  2017-01-08 18:28:03.143765  treatment     new_page          0
4        864975  2017-01-21 01:52:26.210827    control     old_page          1
...         ...                         ...        ...          ...        ...
294473   751197  2017-01-03 22:28:38.630509    control     old_page          0
294474   945152  2017-01-12 00:51:57.078372    control     old_page          0
294475   734608  2017-01-22 11:45:03.439544    control     old_page          0
294476   697314  2017-01-15 01:20:28.957438    control     old_page          0
294477   715931  2017-01-16 12:40:24.467417  treatment     new_page          0

[290584 rows x 5 columns]

In [ ]:
duplicates = df[df['user_id'].duplicated(keep=False)]
print(duplicates)

Empty DataFrame
Columns: [user_id, timestamp, group, landing_page, converted]
Index: []

In [ ]:
#duplicates have been removed

In [ ]:
pd.crosstab(df['group'], df['landing_page'])

landing_page  new_page  old_page
group
control           1006    144226
treatment       144314      1038